import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useW3up } from '@/component/useW3up'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const w3up = useW3up()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Test w3up
        <p>{
          w3up?.agent.did()
        }</p>
      </main>
    </>
  )
}
